"""sender auth and quickbooks cache

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-24 05:29:18.175978
"""

import sqlalchemy as sa
from alembic import op

revision = "0002"
down_revision = "0001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "qbo_accounts",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("fully_qualified_name", sa.String(length=1024), nullable=False),
        sa.Column("account_type", sa.String(length=64), nullable=False),
        sa.Column("account_sub_type", sa.String(length=64), nullable=True),
        sa.Column("acct_num", sa.String(length=32), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "qbo_connections",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("realm_id", sa.String(length=32), nullable=False),
        sa.Column("environment", sa.String(length=16), nullable=False),
        sa.Column("access_token", sa.Text(), nullable=False),
        sa.Column("access_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("refresh_token", sa.Text(), nullable=False),
        sa.Column("refresh_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("connected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("realm_id"),
    )
    op.create_table(
        "qbo_settings",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value", sa.String(length=255), nullable=True),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "qbo_tax_codes",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("purchase_rate", sa.Numeric(precision=7, scale=4), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "qbo_vendors",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("display_name", sa.String(length=500), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_qbo_vendors_display_name"), "qbo_vendors", ["display_name"], unique=False
    )
    op.add_column(
        "inbound_emails",
        sa.Column("sender_auth", sa.String(length=8), nullable=False, server_default="none"),
    )
    op.add_column(
        "inbound_emails",
        sa.Column("sender_auth_detail", sa.JSON(), nullable=False, server_default="{}"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("inbound_emails", "sender_auth_detail")
    op.drop_column("inbound_emails", "sender_auth")
    op.drop_index(op.f("ix_qbo_vendors_display_name"), table_name="qbo_vendors")
    op.drop_table("qbo_vendors")
    op.drop_table("qbo_tax_codes")
    op.drop_table("qbo_settings")
    op.drop_table("qbo_connections")
    op.drop_table("qbo_accounts")
    # ### end Alembic commands ###
